language: python
python:
  - 3.6
before_install:
  - python -- version
  - pip install -u pip
  - pip install codecov
 script:
  - coverage run --source=com/leonardo/ -m unittest discover;coverage report -m
  - python -m unittest discover